### ISSUE TITLE
Error linking sessions-get-and-post with symlink to granada samples

### ISSUE THREAD

**Issue by jjhegedus** [webappsdk/granada#2]
I followed your instructions at https://github.com/webappsdk/granada/wiki/Build-for-Linux-and-MacOS for building granada.  I am using Ubuntu 16.04.1 LTS.

Where is says "...link or put these granada folders respectively in the include, the src and the samples folder of your C++ REST SDK project." I chose to create symbolic links.  I commented out the samples except session-get-and-post.

Everything ran fine until linking when I received the following error.

[100%] Linking CXX executable ../../../Binaries/sessions-get-and-post
c++: error: ../../../Binaries/libcpprest.so.2.9: No such file or directory
samples/granada/sessions-get-and-post/CMakeFiles/sessions-get-and-post.dir/build.make:427: recipe for target 'Binaries/sessions-get-and-post' failed
make[2]: *** [Binaries/sessions-get-and-post] Error 1
CMakeFiles/Makefile2:1028: recipe for target 'samples/granada/sessions-get-and-post/CMakeFiles/sessions-get-and-post.dir/all' failed
make[1]: *** [samples/granada/sessions-get-and-post/CMakeFiles/sessions-get-and-post.dir/all] Error 2
Makefile:138: recipe for target 'all' failed

It works fine when I copy the samples folder instead of making a link (still using links for include and src).  It looks like an issue with relative paths (../../../Binaries) not resolving properly after cd follows the symlink.  Not a big issue since it is just for the samples but I thought you may want to either correct the instructions or update the build to support the symlink.

I'm not terribly comfortable modifying the cpprest project in order to integrate granada.  Based on your comment regarding building for windows at the end of your last post on the issue at https://github.com/webappsdk/granada/issues/1, it looks like it should be possible to build granada as an so on Linux and build the samples referencing that so.  Can you explain your rationale for that choice vs. compiling granada as a separate so that relies on the cpprest so?

I recognize this is more of a discussion than an issue, but it looks like probably the best way to communicate unless you have a preferred alternative.  It has the advantage (and disadvantage ;-) of being available for others to view and learn from.

**Comment by Lvroz** [comment]
Hi,

Thank you for your suggestion,

> I'm not terribly comfortable modifying the cpprest project in order to integrate granada. Based on your comment regarding building for windows at the end of your last post on the issue at #1, it looks like it should be possible to build granada as an so on Linux and build the samples referencing that so. Can you explain your rationale for that choice vs. compiling granada as a separate so that relies on the cpprest so?

I had the same reflexion months before,

This is how I saw things:

I didn't see what I think you call the C++ REST SDK project (I suppose you mean the structure as it is presented in their repository) as the C++ REST SDK library itself (I'm not saying you don't see it the same way). What I saw as cpprest library, is what is in the cpprest directory in include directory and the sources in the src directory. The other files and directories are just a way of structuring a project. I concieved granada as a layer on top of cpprest that should be integrated respecting the structure proposed by Microsoft developpers.

I agree with you, we should be able to create an empty project, and use links of both cpprest and granada without touching the respective projects.

I will look at it,

Thank you again.

**Comment by jjhegedus** [comment]
Thanks for responding.  I apologize that it has taken me so long to respond myself.  I appreciate you sharing your thought process with me.  I think I do see the C++ REST SDK the same.  Your logic makes sense.  I just hadn't thought of it that way.

I would like to get your thoughts on the pros and cons of this method of integration with source code in the same tree vs. integrating as an so.  Is there a significant performance delta?  Would debugging be more difficult?  Are there other reasons you can think of to prefer one over the other?
